version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:30"
  open-pull-requests-limit: 20
  target-branch: develop
  ignore:
  - dependency-name: pyvirtualdisplay
    versions:
    - "2.0"
- package-ecosystem: npm
  directory: "/l2-frontend"
  schedule:
    interval: daily
    time: "02:30"
  open-pull-requests-limit: 20
  target-branch: develop
  ignore:
  - dependency-name: sass-loader
    versions:
    - 10.1.1
